# PostgreSQL
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${IC_POSTGRES_HOST:localhost}:${IC_POSTGRES_PORT:5432}/${IC_POSTGRES_DB:bct}?characterEncoding=UTF-8&stringtype=unspecified
    username: ${IC_POSTGRES_USERNAME:bct}
    password: ${IC_POSTGRES_PASSWORD:kEaLJ9ZERLLN}
    hikari:
      maximum-pool-size: ${IC_DATABASE_MAX_POOL_SIZE:30}
  flyway:
    default-schema: duplicate_snowball
    locations: filesystem:./scripts/db/flyway/pg
    schemas: flyway_schema_history_ds
    out-of-order: true
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher